### ISSUE TITLE
CommandItem components inside options.map doesn't get rerendered when changing options dynamically

### ISSUE THREAD

**Issue by saver711** [sersavan/shadcn-multi-select-component#11]
I tried to implement lazyloading by requesting data from BE upon typing in the search input
new data doesn't get rendered until i close the popover and reopen it

**Comment by sersavan** [comment]
I don't quite understand what exactly isn't working, can you provide me an example?

**Comment by saver711** [comment]
@sersavan Check this video
https://drive.google.com/file/d/17LO-pm7hLUdiEGrdV2HEo5bDw5txBQPC/view?usp=sharing
