### ISSUE TITLE
How to contribute this project?

### ISSUE THREAD

**Issue by YoonHan** [sersavan/shadcn-multi-select-component#14]
Hi! I am quite satisfied the work you have done :)
I'd like to say thanks to you first.

Btw, I need some additional functionalities!

My specific use cases are,
1. I need to disable specific option(s) initially.
2. In the context of `1.` I cannot interact with the disabled option(s) by clicking itself(themselves) or UI elements like 'Clear' button, 'x' icon button, '(Select All)' option item in the list. Even if I click that, there should be no effect on disabled option(s).

I think I am able to implement this functionality in a few hrs. If you don't mind letting me contribute to this functionality, please let me know how to do that!

**Comment by sersavan** [comment]
Hi, thank you for your kind words and appreciation of my component.
You can fork the repository, make your changes, and submit a pull request.
I'll review it promptly.

**Comment by YoonHan** [comment]
Thanks @sersavan! 
I will open a PR for this in this weekend :)
