### ISSUE TITLE
Issue with selectedValues not updating on mount

### ISSUE THREAD

**Issue by vincchan** [sersavan/shadcn-multi-select-component#17]
While implementing the MultiSelect component using controlled form, I noticed a minor issue in the useEffect hook that can arise during the initial mounting phase. The intention appears to be synchronizing the `selectedValues` state with the `defaultValue` prop. 

However, there's an error that can prevent this synchronization from happening correctly when the component first mounts.

Currently, if `defaultValue` is already set when the component mounts and it differs from the initial value of `selectedValues` (which is an empty array), the useEffect will detect this discrepancy. 

However, the subsequent `setSelectedValues(selectedValues);` maintains the existing `selectedValues` instead of updating it to the `defaultValue`.

```javascript
React.useEffect(() => {
  if (JSON.stringify(selectedValues) !== JSON.stringify(defaultValue)) {
    setSelectedValues(selectedValues);
  }
}, [defaultValue, selectedValues]);
```

To fix my problem I've simply set the selected values to the defaultValue

```javascript
React.useEffect(() => {
  if (JSON.stringify(selectedValues) !== JSON.stringify(defaultValue)) {
    setSelectedValues(defaultValue);
  }
}, [defaultValue, selectedValues]);
```

**Comment by sersavan** [comment]
Thanks for pointing that out. However, the solution you suggested might cause an issue where it's impossible to change or select values if there were default (saved) values when the component first loads. 
I suggest trying a different approach with two useEffect hooks. The first one would handle syncing values when the component mounts, and the second would update them when props change. If you can test this approach and give me feedback, I'll update the component based on your findings.

```
    React.useEffect(() => {
      setSelectedValues(defaultValue);
    }, []);

    React.useEffect(() => {
      if (JSON.stringify(selectedValues) !== JSON.stringify(defaultValue)) {
        setSelectedValues(selectedValues);
      }
    }, [selectedValues]);
```

**Comment by sersavan** [comment]
Or even try only this:

```
React.useEffect(() => {
      if (JSON.stringify(selectedValues) !== JSON.stringify(defaultValue)) {
        setSelectedValues(selectedValues);
      }
    }, [selectedValues]);
```

**Comment by sersavan** [comment]
Fixed

**Comment by vincchan** [comment]
Thank you 👍
