### ISSUE TITLE
TypeScript compiler is unable to iterate through the Set

### ISSUE THREAD

**Issue by lenocin** [sersavan/shadcn-multi-select-component#2]
Great work.  I managed to resolve the TS error I get with my NextJS [14] project

What you think?

```
    const toggleOption = (value: string) => {
      if (selectedValuesSet.current.has(value)) {
        selectedValuesSet.current.delete(value);
        setSelectedValues(selectedValues.filter((v) => v !== value));
      } else {
        selectedValuesSet.current.add(value);
        setSelectedValues([...selectedValues, value]);
      }
      onValueChange(Array.from(selectedValuesSet.current));
    };
```

**Comment by sersavan** [comment]
@lenocin 
Thanks, I will check your proposal.
In my case I resolved this problem by adding "target": "es2015" into tsconfig.json

![image](https://github.com/sersavan/shadcn-multi-select-component/assets/3727722/a24e69f7-d4f3-437e-bd9e-d0aa9d2dc719)
