### ISSUE TITLE
Scroll doesn't work in Dialog

### ISSUE THREAD

**Issue by sebi75** [sersavan/shadcn-multi-select-component#33]
When there are enough items to overflow the container's height, scrolling doesn't work in a Dialog.

- Scrolling does work if you're using the component in the document, outside of a dialog

**Comment by Wakadaisho** [comment]
There's a modalPopover prop that you can set to true to enable it to work. Not sure if that is its intended use, but nothing breaks and the scroll works. :)

**Comment by sebi75** [comment]
> There's a modalPopover prop that you can set to true to enable it to work. Not sure if that is its intended use, but nothing breaks and the scroll works. :)

Awesome, that works perfectly, thanks!
I think it may actually be the intended use to make it work in dialogs.
