### ISSUE TITLE
Cannot scroll item on mobile device and desktop

### ISSUE THREAD

**Issue by beysach** [sersavan/shadcn-multi-select-component#6]
I'm experiencing an issue where I'm unable to use the scroll mouse wheel and scroll touch on a mobile phone. This issue persists across various browsers and devices. 

https://github.com/sersavan/shadcn-multi-select-component/assets/24478705/ffcb5827-5e84-4820-8b3f-8930e4b0decf

**Comment by sersavan** [comment]
Hi, in my applications the component works successfully on mobile phones, scrolling and selecting values ​​from the command menu work correctly. My advice, check and, if necessary, update the command component to the latest version.
`npx shadcn-ui@latest add command`

**Comment by beysach** [comment]
I fixed it by add ```modal={true}``` to ```<Popover open={isPopoverOpen} onOpenChange={setIsPopoverOpen} modal={true}>```. 
here is the reference https://github.com/shadcn-ui/ui/issues/542

**Comment by sersavan** [comment]
OK, I'll add this parameter as a prop for those who need this behavior
![image](https://github.com/sersavan/shadcn-multi-select-component/assets/3727722/f04bfc75-ef73-41e9-830c-5a638ae919d8)

**Comment by sersavan** [comment]
done

**Comment by beysach** [comment]
thank you
