### ISSUE TITLE
[BUG] Mouse Click Doesn't work but keyboard buttons are working

### ISSUE THREAD

**Issue by anshumalivfx** [sersavan/shadcn-multi-select-component#9]
I don't know whats going on here but it looks mouse click is not working with React Hook Forms but keyboards button seems to be working

<img width="683" alt="Screenshot 2024-07-20 at 17 15 36" src="https://github.com/user-attachments/assets/d42a16a3-f836-4169-a2d1-10c66323a836">

**Comment by sersavan** [comment]
Update `npx shadcn-ui@latest add command
`

**Comment by anshumalivfx** [comment]
@sersavan I just used https://github.com/sersavan/shadcn-multi-select-component/blob/main/src/components/ui/command.tsx Repository version of command and it started to work
